-- Initial setup for Diesel migrations
-- This migration is automatically generated by Diesel

-- Diesel internal table for tracking migrations
-- This will be created automatically by diesel_migrations
