package main

/*
// Generated by rust2go. Please DO NOT edit this C part manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ListRef {
  const void *ptr;
  uintptr_t len;
} ListRef;

typedef struct ChaCha20Poly1305DecryptRequestRef {
  struct ListRef key;
  struct ListRef nonce;
  struct ListRef ciphertext;
  struct ListRef additional_data;
} ChaCha20Poly1305DecryptRequestRef;

typedef struct StringRef {
  const uint8_t *ptr;
  uintptr_t len;
} StringRef;

typedef struct ChaCha20Poly1305DecryptResponseRef {
  struct ListRef plaintext;
  bool success;
  struct StringRef error;
} ChaCha20Poly1305DecryptResponseRef;

typedef struct ChaCha20Poly1305EncryptRequestRef {
  struct ListRef key;
  struct ListRef nonce;
  struct ListRef plaintext;
  struct ListRef additional_data;
} ChaCha20Poly1305EncryptRequestRef;

typedef struct ChaCha20Poly1305EncryptResponseRef {
  struct ListRef ciphertext;
  bool success;
  struct StringRef error;
} ChaCha20Poly1305EncryptResponseRef;

typedef struct Ed25519GenerateKeyRequestRef {

} Ed25519GenerateKeyRequestRef;

typedef struct Ed25519GenerateKeyResponseRef {
  struct ListRef public_key;
  struct ListRef private_key;
  bool success;
  struct StringRef error;
} Ed25519GenerateKeyResponseRef;

typedef struct Ed25519SignRequestRef {
  struct ListRef private_key;
  struct ListRef message;
} Ed25519SignRequestRef;

typedef struct Ed25519SignResponseRef {
  struct ListRef signature;
  bool success;
  struct StringRef error;
} Ed25519SignResponseRef;

typedef struct Ed25519VerifyRequestRef {
  struct ListRef public_key;
  struct ListRef message;
  struct ListRef signature;
} Ed25519VerifyRequestRef;

typedef struct Ed25519VerifyResponseRef {
  bool valid;
  bool success;
  struct StringRef error;
} Ed25519VerifyResponseRef;

typedef struct MfaLoginBeginRequestRef {
  struct StringRef username;
  struct StringRef mediation;
} MfaLoginBeginRequestRef;

typedef struct MfaLoginBeginResponseRef {
  struct StringRef session_id;
  struct StringRef challenge_json;
  bool success;
  struct StringRef error;
} MfaLoginBeginResponseRef;

typedef struct MfaLoginFinishRequestRef {
  struct StringRef session_id;
  struct StringRef credential_json;
} MfaLoginFinishRequestRef;

typedef struct MfaLoginFinishResponseRef {
  bool success;
  struct StringRef user_id;
  struct StringRef session_token;
  struct StringRef error;
} MfaLoginFinishResponseRef;

typedef struct PasskeyLoginBeginRequestRef {
  struct StringRef mediation;
} PasskeyLoginBeginRequestRef;

typedef struct PasskeyLoginBeginResponseRef {
  struct StringRef session_id;
  struct StringRef challenge_json;
  bool success;
  struct StringRef error;
} PasskeyLoginBeginResponseRef;

typedef struct PasskeyLoginFinishRequestRef {
  struct StringRef session_id;
  struct StringRef credential_json;
} PasskeyLoginFinishRequestRef;

typedef struct PasskeyLoginFinishResponseRef {
  bool success;
  struct StringRef user_id;
  struct StringRef username;
  struct StringRef session_token;
  struct StringRef error;
} PasskeyLoginFinishResponseRef;

typedef struct SigninBeginRequestRef {
  struct StringRef username;
  struct StringRef scenario;
} SigninBeginRequestRef;

typedef struct SigninBeginResponseRef {
  struct StringRef session_id;
  struct StringRef challenge_json;
  bool success;
  struct StringRef error;
} SigninBeginResponseRef;

typedef struct SigninFinishRequestRef {
  struct StringRef session_id;
  struct StringRef credential_json;
} SigninFinishRequestRef;

typedef struct SigninFinishResponseRef {
  bool success;
  struct StringRef user_id;
  struct StringRef session_token;
  struct StringRef error;
} SigninFinishResponseRef;

typedef struct SignupBeginRequestRef {
  struct StringRef username;
  struct StringRef display_name;
  struct StringRef scenario;
} SignupBeginRequestRef;

typedef struct SignupBeginResponseRef {
  struct StringRef session_id;
  struct StringRef challenge_json;
  bool success;
  struct StringRef error;
} SignupBeginResponseRef;

typedef struct SignupFinishRequestRef {
  struct StringRef session_id;
  struct StringRef credential_json;
} SignupFinishRequestRef;

typedef struct SignupFinishResponseRef {
  bool success;
  struct StringRef user_id;
  struct StringRef error;
} SignupFinishResponseRef;
*/
import "C"
import (
	"runtime"
	"unsafe"

	"github.com/ihciah/rust2go/asmcall"
)

var WebAuthnBridgeImpl WebAuthnBridge

type WebAuthnBridge interface {
	signup_begin(req SignupBeginRequest) SignupBeginResponse
	signup_finish(req SignupFinishRequest) SignupFinishResponse
	signin_begin(req SigninBeginRequest) SigninBeginResponse
	signin_finish(req SigninFinishRequest) SigninFinishResponse
	passkey_login_begin(req PasskeyLoginBeginRequest) PasskeyLoginBeginResponse
	passkey_login_finish(req PasskeyLoginFinishRequest) PasskeyLoginFinishResponse
	mfa_login_begin(req MfaLoginBeginRequest) MfaLoginBeginResponse
	mfa_login_finish(req MfaLoginFinishRequest) MfaLoginFinishResponse
}

//export CWebAuthnBridge_signup_begin
func CWebAuthnBridge_signup_begin(req C.SignupBeginRequestRef, slot *C.void, cb *C.void) {
	_new_req := newSignupBeginRequest(req)
	go func() {
		resp := WebAuthnBridgeImpl.signup_begin(_new_req)
		resp_ref, buffer := cvt_ref(cntSignupBeginResponse, refSignupBeginResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CWebAuthnBridge_signup_finish
func CWebAuthnBridge_signup_finish(req C.SignupFinishRequestRef, slot *C.void, cb *C.void) {
	_new_req := newSignupFinishRequest(req)
	go func() {
		resp := WebAuthnBridgeImpl.signup_finish(_new_req)
		resp_ref, buffer := cvt_ref(cntSignupFinishResponse, refSignupFinishResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CWebAuthnBridge_signin_begin
func CWebAuthnBridge_signin_begin(req C.SigninBeginRequestRef, slot *C.void, cb *C.void) {
	_new_req := newSigninBeginRequest(req)
	go func() {
		resp := WebAuthnBridgeImpl.signin_begin(_new_req)
		resp_ref, buffer := cvt_ref(cntSigninBeginResponse, refSigninBeginResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CWebAuthnBridge_signin_finish
func CWebAuthnBridge_signin_finish(req C.SigninFinishRequestRef, slot *C.void, cb *C.void) {
	_new_req := newSigninFinishRequest(req)
	go func() {
		resp := WebAuthnBridgeImpl.signin_finish(_new_req)
		resp_ref, buffer := cvt_ref(cntSigninFinishResponse, refSigninFinishResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CWebAuthnBridge_passkey_login_begin
func CWebAuthnBridge_passkey_login_begin(req C.PasskeyLoginBeginRequestRef, slot *C.void, cb *C.void) {
	_new_req := newPasskeyLoginBeginRequest(req)
	go func() {
		resp := WebAuthnBridgeImpl.passkey_login_begin(_new_req)
		resp_ref, buffer := cvt_ref(cntPasskeyLoginBeginResponse, refPasskeyLoginBeginResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CWebAuthnBridge_passkey_login_finish
func CWebAuthnBridge_passkey_login_finish(req C.PasskeyLoginFinishRequestRef, slot *C.void, cb *C.void) {
	_new_req := newPasskeyLoginFinishRequest(req)
	go func() {
		resp := WebAuthnBridgeImpl.passkey_login_finish(_new_req)
		resp_ref, buffer := cvt_ref(cntPasskeyLoginFinishResponse, refPasskeyLoginFinishResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CWebAuthnBridge_mfa_login_begin
func CWebAuthnBridge_mfa_login_begin(req C.MfaLoginBeginRequestRef, slot *C.void, cb *C.void) {
	_new_req := newMfaLoginBeginRequest(req)
	go func() {
		resp := WebAuthnBridgeImpl.mfa_login_begin(_new_req)
		resp_ref, buffer := cvt_ref(cntMfaLoginBeginResponse, refMfaLoginBeginResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CWebAuthnBridge_mfa_login_finish
func CWebAuthnBridge_mfa_login_finish(req C.MfaLoginFinishRequestRef, slot *C.void, cb *C.void) {
	_new_req := newMfaLoginFinishRequest(req)
	go func() {
		resp := WebAuthnBridgeImpl.mfa_login_finish(_new_req)
		resp_ref, buffer := cvt_ref(cntMfaLoginFinishResponse, refMfaLoginFinishResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

var CryptoBridgeImpl CryptoBridge

type CryptoBridge interface {
	chacha20poly1305_encrypt(req *ChaCha20Poly1305EncryptRequest) ChaCha20Poly1305EncryptResponse
	chacha20poly1305_decrypt(req *ChaCha20Poly1305DecryptRequest) ChaCha20Poly1305DecryptResponse
	ed25519_generate_key(req *Ed25519GenerateKeyRequest) Ed25519GenerateKeyResponse
	ed25519_sign(req *Ed25519SignRequest) Ed25519SignResponse
	ed25519_verify(req *Ed25519VerifyRequest) Ed25519VerifyResponse
}

//export CCryptoBridge_chacha20poly1305_encrypt
func CCryptoBridge_chacha20poly1305_encrypt(req C.ChaCha20Poly1305EncryptRequestRef, slot *C.void, cb *C.void) {
	_new_req := newChaCha20Poly1305EncryptRequest(req)
	go func() {
		resp := CryptoBridgeImpl.chacha20poly1305_encrypt(&_new_req)
		resp_ref, buffer := cvt_ref(cntChaCha20Poly1305EncryptResponse, refChaCha20Poly1305EncryptResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CCryptoBridge_chacha20poly1305_decrypt
func CCryptoBridge_chacha20poly1305_decrypt(req C.ChaCha20Poly1305DecryptRequestRef, slot *C.void, cb *C.void) {
	_new_req := newChaCha20Poly1305DecryptRequest(req)
	go func() {
		resp := CryptoBridgeImpl.chacha20poly1305_decrypt(&_new_req)
		resp_ref, buffer := cvt_ref(cntChaCha20Poly1305DecryptResponse, refChaCha20Poly1305DecryptResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CCryptoBridge_ed25519_generate_key
func CCryptoBridge_ed25519_generate_key(req C.Ed25519GenerateKeyRequestRef, slot *C.void, cb *C.void) {
	_new_req := newEd25519GenerateKeyRequest(req)
	go func() {
		resp := CryptoBridgeImpl.ed25519_generate_key(&_new_req)
		resp_ref, buffer := cvt_ref(cntEd25519GenerateKeyResponse, refEd25519GenerateKeyResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CCryptoBridge_ed25519_sign
func CCryptoBridge_ed25519_sign(req C.Ed25519SignRequestRef, slot *C.void, cb *C.void) {
	_new_req := newEd25519SignRequest(req)
	go func() {
		resp := CryptoBridgeImpl.ed25519_sign(&_new_req)
		resp_ref, buffer := cvt_ref(cntEd25519SignResponse, refEd25519SignResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

//export CCryptoBridge_ed25519_verify
func CCryptoBridge_ed25519_verify(req C.Ed25519VerifyRequestRef, slot *C.void, cb *C.void) {
	_new_req := newEd25519VerifyRequest(req)
	go func() {
		resp := CryptoBridgeImpl.ed25519_verify(&_new_req)
		resp_ref, buffer := cvt_ref(cntEd25519VerifyResponse, refEd25519VerifyResponse)(&resp)
		asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
		runtime.KeepAlive(resp_ref)
		runtime.KeepAlive(resp)
		runtime.KeepAlive(buffer)
	}()
}

func newString(s_ref C.StringRef) string {
	return unsafe.String((*byte)(unsafe.Pointer(s_ref.ptr)), s_ref.len)
}
func refString(s *string, _ *[]byte) C.StringRef {
	return C.StringRef{
		ptr: (*C.uint8_t)(unsafe.StringData(*s)),
		len: C.uintptr_t(len(*s)),
	}
}

func ownString(s_ref C.StringRef) string {
	return string(unsafe.Slice((*byte)(unsafe.Pointer(s_ref.ptr)), int(s_ref.len)))
}
func cntString(_ *string, _ *uint) [0]C.StringRef { return [0]C.StringRef{} }
func new_list_mapper[T1, T2 any](f func(T1) T2) func(C.ListRef) []T2 {
	return func(x C.ListRef) []T2 {
		input := unsafe.Slice((*T1)(unsafe.Pointer(x.ptr)), x.len)
		output := make([]T2, len(input))
		for i, v := range input {
			output[i] = f(v)
		}
		return output
	}
}
func new_list_mapper_primitive[T1, T2 any](_ func(T1) T2) func(C.ListRef) []T2 {
	return func(x C.ListRef) []T2 {
		return unsafe.Slice((*T2)(unsafe.Pointer(x.ptr)), x.len)
	}
}

// only handle non-primitive type T
func cnt_list_mapper[T, R any](f func(s *T, cnt *uint) [0]R) func(s *[]T, cnt *uint) [0]C.ListRef {
	return func(s *[]T, cnt *uint) [0]C.ListRef {
		for _, v := range *s {
			f(&v, cnt)
		}
		*cnt += uint(len(*s)) * size_of[R]()
		return [0]C.ListRef{}
	}
}

// only handle primitive type T
func cnt_list_mapper_primitive[T, R any](_ func(s *T, cnt *uint) [0]R) func(s *[]T, cnt *uint) [0]C.ListRef {
	return func(s *[]T, cnt *uint) [0]C.ListRef { return [0]C.ListRef{} }
}

// only handle non-primitive type T
func ref_list_mapper[T, R any](f func(s *T, buffer *[]byte) R) func(s *[]T, buffer *[]byte) C.ListRef {
	return func(s *[]T, buffer *[]byte) C.ListRef {
		if len(*buffer) == 0 {
			return C.ListRef{
				ptr: unsafe.Pointer(nil),
				len: C.uintptr_t(len(*s)),
			}
		}
		ret := C.ListRef{
			ptr: unsafe.Pointer(&(*buffer)[0]),
			len: C.uintptr_t(len(*s)),
		}
		children_bytes := int(size_of[R]()) * len(*s)
		children := (*buffer)[:children_bytes]
		*buffer = (*buffer)[children_bytes:]
		for _, v := range *s {
			child := f(&v, buffer)
			len := unsafe.Sizeof(child)
			copy(children, unsafe.Slice((*byte)(unsafe.Pointer(&child)), len))
			children = children[len:]
		}
		return ret
	}
}

// only handle primitive type T
func ref_list_mapper_primitive[T, R any](_ func(s *T, buffer *[]byte) R) func(s *[]T, buffer *[]byte) C.ListRef {
	return func(s *[]T, buffer *[]byte) C.ListRef {
		if len(*s) == 0 {
			return C.ListRef{
				ptr: unsafe.Pointer(nil),
				len: C.uintptr_t(0),
			}
		}
		return C.ListRef{
			ptr: unsafe.Pointer(&(*s)[0]),
			len: C.uintptr_t(len(*s)),
		}
	}
}
func size_of[T any]() uint {
	var t T
	return uint(unsafe.Sizeof(t))
}
func cvt_ref[R, CR any](cnt_f func(s *R, cnt *uint) [0]CR, ref_f func(p *R, buffer *[]byte) CR) func(p *R) (CR, []byte) {
	return func(p *R) (CR, []byte) {
		var cnt uint
		cnt_f(p, &cnt)
		buffer := make([]byte, cnt)
		return ref_f(p, &buffer), buffer
	}
}
func cvt_ref_cap[R, CR any](cnt_f func(s *R, cnt *uint) [0]CR, ref_f func(p *R, buffer *[]byte) CR, add_cap uint) func(p *R) (CR, []byte) {
	return func(p *R) (CR, []byte) {
		var cnt uint
		cnt_f(p, &cnt)
		buffer := make([]byte, cnt, cnt+add_cap)
		return ref_f(p, &buffer), buffer
	}
}

func newC_uint8_t(n C.uint8_t) uint8    { return uint8(n) }
func newC_uint16_t(n C.uint16_t) uint16 { return uint16(n) }
func newC_uint32_t(n C.uint32_t) uint32 { return uint32(n) }
func newC_uint64_t(n C.uint64_t) uint64 { return uint64(n) }
func newC_int8_t(n C.int8_t) int8       { return int8(n) }
func newC_int16_t(n C.int16_t) int16    { return int16(n) }
func newC_int32_t(n C.int32_t) int32    { return int32(n) }
func newC_int64_t(n C.int64_t) int64    { return int64(n) }
func newC_bool(n C.bool) bool           { return bool(n) }
func newC_uintptr_t(n C.uintptr_t) uint { return uint(n) }
func newC_intptr_t(n C.intptr_t) int    { return int(n) }
func newC_float(n C.float) float32      { return float32(n) }
func newC_double(n C.double) float64    { return float64(n) }

func cntC_uint8_t(_ *uint8, _ *uint) [0]C.uint8_t    { return [0]C.uint8_t{} }
func cntC_uint16_t(_ *uint16, _ *uint) [0]C.uint16_t { return [0]C.uint16_t{} }
func cntC_uint32_t(_ *uint32, _ *uint) [0]C.uint32_t { return [0]C.uint32_t{} }
func cntC_uint64_t(_ *uint64, _ *uint) [0]C.uint64_t { return [0]C.uint64_t{} }
func cntC_int8_t(_ *int8, _ *uint) [0]C.int8_t       { return [0]C.int8_t{} }
func cntC_int16_t(_ *int16, _ *uint) [0]C.int16_t    { return [0]C.int16_t{} }
func cntC_int32_t(_ *int32, _ *uint) [0]C.int32_t    { return [0]C.int32_t{} }
func cntC_int64_t(_ *int64, _ *uint) [0]C.int64_t    { return [0]C.int64_t{} }
func cntC_bool(_ *bool, _ *uint) [0]C.bool           { return [0]C.bool{} }
func cntC_uintptr_t(_ *uint, _ *uint) [0]C.uintptr_t { return [0]C.uintptr_t{} }
func cntC_intptr_t(_ *int, _ *uint) [0]C.intptr_t    { return [0]C.intptr_t{} }
func cntC_float(_ *float32, _ *uint) [0]C.float      { return [0]C.float{} }
func cntC_double(_ *float64, _ *uint) [0]C.double    { return [0]C.double{} }

func refC_uint8_t(p *uint8, _ *[]byte) C.uint8_t    { return C.uint8_t(*p) }
func refC_uint16_t(p *uint16, _ *[]byte) C.uint16_t { return C.uint16_t(*p) }
func refC_uint32_t(p *uint32, _ *[]byte) C.uint32_t { return C.uint32_t(*p) }
func refC_uint64_t(p *uint64, _ *[]byte) C.uint64_t { return C.uint64_t(*p) }
func refC_int8_t(p *int8, _ *[]byte) C.int8_t       { return C.int8_t(*p) }
func refC_int16_t(p *int16, _ *[]byte) C.int16_t    { return C.int16_t(*p) }
func refC_int32_t(p *int32, _ *[]byte) C.int32_t    { return C.int32_t(*p) }
func refC_int64_t(p *int64, _ *[]byte) C.int64_t    { return C.int64_t(*p) }
func refC_bool(p *bool, _ *[]byte) C.bool           { return C.bool(*p) }
func refC_uintptr_t(p *uint, _ *[]byte) C.uintptr_t { return C.uintptr_t(*p) }
func refC_intptr_t(p *int, _ *[]byte) C.intptr_t    { return C.intptr_t(*p) }
func refC_float(p *float32, _ *[]byte) C.float      { return C.float(*p) }
func refC_double(p *float64, _ *[]byte) C.double    { return C.double(*p) }

type SignupBeginRequest struct {
	username     string
	display_name string
	scenario     string
}

func newSignupBeginRequest(p C.SignupBeginRequestRef) SignupBeginRequest {
	return SignupBeginRequest{
		username:     newString(p.username),
		display_name: newString(p.display_name),
		scenario:     newString(p.scenario),
	}
}
func ownSignupBeginRequest(p C.SignupBeginRequestRef) SignupBeginRequest {
	return SignupBeginRequest{
		username:     ownString(p.username),
		display_name: ownString(p.display_name),
		scenario:     ownString(p.scenario),
	}
}
func cntSignupBeginRequest(s *SignupBeginRequest, cnt *uint) [0]C.SignupBeginRequestRef {
	_ = s
	_ = cnt
	return [0]C.SignupBeginRequestRef{}
}
func refSignupBeginRequest(p *SignupBeginRequest, buffer *[]byte) C.SignupBeginRequestRef {
	return C.SignupBeginRequestRef{
		username:     refString(&p.username, buffer),
		display_name: refString(&p.display_name, buffer),
		scenario:     refString(&p.scenario, buffer),
	}
}

type SignupBeginResponse struct {
	session_id     string
	challenge_json string
	success        bool
	error          string
}

func newSignupBeginResponse(p C.SignupBeginResponseRef) SignupBeginResponse {
	return SignupBeginResponse{
		session_id:     newString(p.session_id),
		challenge_json: newString(p.challenge_json),
		success:        newC_bool(p.success),
		error:          newString(p.error),
	}
}
func ownSignupBeginResponse(p C.SignupBeginResponseRef) SignupBeginResponse {
	return SignupBeginResponse{
		session_id:     ownString(p.session_id),
		challenge_json: ownString(p.challenge_json),
		success:        newC_bool(p.success),
		error:          ownString(p.error),
	}
}
func cntSignupBeginResponse(s *SignupBeginResponse, cnt *uint) [0]C.SignupBeginResponseRef {
	_ = s
	_ = cnt
	return [0]C.SignupBeginResponseRef{}
}
func refSignupBeginResponse(p *SignupBeginResponse, buffer *[]byte) C.SignupBeginResponseRef {
	return C.SignupBeginResponseRef{
		session_id:     refString(&p.session_id, buffer),
		challenge_json: refString(&p.challenge_json, buffer),
		success:        refC_bool(&p.success, buffer),
		error:          refString(&p.error, buffer),
	}
}

type SignupFinishRequest struct {
	session_id      string
	credential_json string
}

func newSignupFinishRequest(p C.SignupFinishRequestRef) SignupFinishRequest {
	return SignupFinishRequest{
		session_id:      newString(p.session_id),
		credential_json: newString(p.credential_json),
	}
}
func ownSignupFinishRequest(p C.SignupFinishRequestRef) SignupFinishRequest {
	return SignupFinishRequest{
		session_id:      ownString(p.session_id),
		credential_json: ownString(p.credential_json),
	}
}
func cntSignupFinishRequest(s *SignupFinishRequest, cnt *uint) [0]C.SignupFinishRequestRef {
	_ = s
	_ = cnt
	return [0]C.SignupFinishRequestRef{}
}
func refSignupFinishRequest(p *SignupFinishRequest, buffer *[]byte) C.SignupFinishRequestRef {
	return C.SignupFinishRequestRef{
		session_id:      refString(&p.session_id, buffer),
		credential_json: refString(&p.credential_json, buffer),
	}
}

type SignupFinishResponse struct {
	success bool
	user_id string
	error   string
}

func newSignupFinishResponse(p C.SignupFinishResponseRef) SignupFinishResponse {
	return SignupFinishResponse{
		success: newC_bool(p.success),
		user_id: newString(p.user_id),
		error:   newString(p.error),
	}
}
func ownSignupFinishResponse(p C.SignupFinishResponseRef) SignupFinishResponse {
	return SignupFinishResponse{
		success: newC_bool(p.success),
		user_id: ownString(p.user_id),
		error:   ownString(p.error),
	}
}
func cntSignupFinishResponse(s *SignupFinishResponse, cnt *uint) [0]C.SignupFinishResponseRef {
	_ = s
	_ = cnt
	return [0]C.SignupFinishResponseRef{}
}
func refSignupFinishResponse(p *SignupFinishResponse, buffer *[]byte) C.SignupFinishResponseRef {
	return C.SignupFinishResponseRef{
		success: refC_bool(&p.success, buffer),
		user_id: refString(&p.user_id, buffer),
		error:   refString(&p.error, buffer),
	}
}

type SigninBeginRequest struct {
	username string
	scenario string
}

func newSigninBeginRequest(p C.SigninBeginRequestRef) SigninBeginRequest {
	return SigninBeginRequest{
		username: newString(p.username),
		scenario: newString(p.scenario),
	}
}
func ownSigninBeginRequest(p C.SigninBeginRequestRef) SigninBeginRequest {
	return SigninBeginRequest{
		username: ownString(p.username),
		scenario: ownString(p.scenario),
	}
}
func cntSigninBeginRequest(s *SigninBeginRequest, cnt *uint) [0]C.SigninBeginRequestRef {
	_ = s
	_ = cnt
	return [0]C.SigninBeginRequestRef{}
}
func refSigninBeginRequest(p *SigninBeginRequest, buffer *[]byte) C.SigninBeginRequestRef {
	return C.SigninBeginRequestRef{
		username: refString(&p.username, buffer),
		scenario: refString(&p.scenario, buffer),
	}
}

type SigninBeginResponse struct {
	session_id     string
	challenge_json string
	success        bool
	error          string
}

func newSigninBeginResponse(p C.SigninBeginResponseRef) SigninBeginResponse {
	return SigninBeginResponse{
		session_id:     newString(p.session_id),
		challenge_json: newString(p.challenge_json),
		success:        newC_bool(p.success),
		error:          newString(p.error),
	}
}
func ownSigninBeginResponse(p C.SigninBeginResponseRef) SigninBeginResponse {
	return SigninBeginResponse{
		session_id:     ownString(p.session_id),
		challenge_json: ownString(p.challenge_json),
		success:        newC_bool(p.success),
		error:          ownString(p.error),
	}
}
func cntSigninBeginResponse(s *SigninBeginResponse, cnt *uint) [0]C.SigninBeginResponseRef {
	_ = s
	_ = cnt
	return [0]C.SigninBeginResponseRef{}
}
func refSigninBeginResponse(p *SigninBeginResponse, buffer *[]byte) C.SigninBeginResponseRef {
	return C.SigninBeginResponseRef{
		session_id:     refString(&p.session_id, buffer),
		challenge_json: refString(&p.challenge_json, buffer),
		success:        refC_bool(&p.success, buffer),
		error:          refString(&p.error, buffer),
	}
}

type SigninFinishRequest struct {
	session_id      string
	credential_json string
}

func newSigninFinishRequest(p C.SigninFinishRequestRef) SigninFinishRequest {
	return SigninFinishRequest{
		session_id:      newString(p.session_id),
		credential_json: newString(p.credential_json),
	}
}
func ownSigninFinishRequest(p C.SigninFinishRequestRef) SigninFinishRequest {
	return SigninFinishRequest{
		session_id:      ownString(p.session_id),
		credential_json: ownString(p.credential_json),
	}
}
func cntSigninFinishRequest(s *SigninFinishRequest, cnt *uint) [0]C.SigninFinishRequestRef {
	_ = s
	_ = cnt
	return [0]C.SigninFinishRequestRef{}
}
func refSigninFinishRequest(p *SigninFinishRequest, buffer *[]byte) C.SigninFinishRequestRef {
	return C.SigninFinishRequestRef{
		session_id:      refString(&p.session_id, buffer),
		credential_json: refString(&p.credential_json, buffer),
	}
}

type SigninFinishResponse struct {
	success       bool
	user_id       string
	session_token string
	error         string
}

func newSigninFinishResponse(p C.SigninFinishResponseRef) SigninFinishResponse {
	return SigninFinishResponse{
		success:       newC_bool(p.success),
		user_id:       newString(p.user_id),
		session_token: newString(p.session_token),
		error:         newString(p.error),
	}
}
func ownSigninFinishResponse(p C.SigninFinishResponseRef) SigninFinishResponse {
	return SigninFinishResponse{
		success:       newC_bool(p.success),
		user_id:       ownString(p.user_id),
		session_token: ownString(p.session_token),
		error:         ownString(p.error),
	}
}
func cntSigninFinishResponse(s *SigninFinishResponse, cnt *uint) [0]C.SigninFinishResponseRef {
	_ = s
	_ = cnt
	return [0]C.SigninFinishResponseRef{}
}
func refSigninFinishResponse(p *SigninFinishResponse, buffer *[]byte) C.SigninFinishResponseRef {
	return C.SigninFinishResponseRef{
		success:       refC_bool(&p.success, buffer),
		user_id:       refString(&p.user_id, buffer),
		session_token: refString(&p.session_token, buffer),
		error:         refString(&p.error, buffer),
	}
}

type PasskeyLoginBeginRequest struct {
	mediation string
}

func newPasskeyLoginBeginRequest(p C.PasskeyLoginBeginRequestRef) PasskeyLoginBeginRequest {
	return PasskeyLoginBeginRequest{
		mediation: newString(p.mediation),
	}
}
func ownPasskeyLoginBeginRequest(p C.PasskeyLoginBeginRequestRef) PasskeyLoginBeginRequest {
	return PasskeyLoginBeginRequest{
		mediation: ownString(p.mediation),
	}
}
func cntPasskeyLoginBeginRequest(s *PasskeyLoginBeginRequest, cnt *uint) [0]C.PasskeyLoginBeginRequestRef {
	_ = s
	_ = cnt
	return [0]C.PasskeyLoginBeginRequestRef{}
}
func refPasskeyLoginBeginRequest(p *PasskeyLoginBeginRequest, buffer *[]byte) C.PasskeyLoginBeginRequestRef {
	return C.PasskeyLoginBeginRequestRef{
		mediation: refString(&p.mediation, buffer),
	}
}

type PasskeyLoginBeginResponse struct {
	session_id     string
	challenge_json string
	success        bool
	error          string
}

func newPasskeyLoginBeginResponse(p C.PasskeyLoginBeginResponseRef) PasskeyLoginBeginResponse {
	return PasskeyLoginBeginResponse{
		session_id:     newString(p.session_id),
		challenge_json: newString(p.challenge_json),
		success:        newC_bool(p.success),
		error:          newString(p.error),
	}
}
func ownPasskeyLoginBeginResponse(p C.PasskeyLoginBeginResponseRef) PasskeyLoginBeginResponse {
	return PasskeyLoginBeginResponse{
		session_id:     ownString(p.session_id),
		challenge_json: ownString(p.challenge_json),
		success:        newC_bool(p.success),
		error:          ownString(p.error),
	}
}
func cntPasskeyLoginBeginResponse(s *PasskeyLoginBeginResponse, cnt *uint) [0]C.PasskeyLoginBeginResponseRef {
	_ = s
	_ = cnt
	return [0]C.PasskeyLoginBeginResponseRef{}
}
func refPasskeyLoginBeginResponse(p *PasskeyLoginBeginResponse, buffer *[]byte) C.PasskeyLoginBeginResponseRef {
	return C.PasskeyLoginBeginResponseRef{
		session_id:     refString(&p.session_id, buffer),
		challenge_json: refString(&p.challenge_json, buffer),
		success:        refC_bool(&p.success, buffer),
		error:          refString(&p.error, buffer),
	}
}

type PasskeyLoginFinishRequest struct {
	session_id      string
	credential_json string
}

func newPasskeyLoginFinishRequest(p C.PasskeyLoginFinishRequestRef) PasskeyLoginFinishRequest {
	return PasskeyLoginFinishRequest{
		session_id:      newString(p.session_id),
		credential_json: newString(p.credential_json),
	}
}
func ownPasskeyLoginFinishRequest(p C.PasskeyLoginFinishRequestRef) PasskeyLoginFinishRequest {
	return PasskeyLoginFinishRequest{
		session_id:      ownString(p.session_id),
		credential_json: ownString(p.credential_json),
	}
}
func cntPasskeyLoginFinishRequest(s *PasskeyLoginFinishRequest, cnt *uint) [0]C.PasskeyLoginFinishRequestRef {
	_ = s
	_ = cnt
	return [0]C.PasskeyLoginFinishRequestRef{}
}
func refPasskeyLoginFinishRequest(p *PasskeyLoginFinishRequest, buffer *[]byte) C.PasskeyLoginFinishRequestRef {
	return C.PasskeyLoginFinishRequestRef{
		session_id:      refString(&p.session_id, buffer),
		credential_json: refString(&p.credential_json, buffer),
	}
}

type PasskeyLoginFinishResponse struct {
	success       bool
	user_id       string
	username      string
	session_token string
	error         string
}

func newPasskeyLoginFinishResponse(p C.PasskeyLoginFinishResponseRef) PasskeyLoginFinishResponse {
	return PasskeyLoginFinishResponse{
		success:       newC_bool(p.success),
		user_id:       newString(p.user_id),
		username:      newString(p.username),
		session_token: newString(p.session_token),
		error:         newString(p.error),
	}
}
func ownPasskeyLoginFinishResponse(p C.PasskeyLoginFinishResponseRef) PasskeyLoginFinishResponse {
	return PasskeyLoginFinishResponse{
		success:       newC_bool(p.success),
		user_id:       ownString(p.user_id),
		username:      ownString(p.username),
		session_token: ownString(p.session_token),
		error:         ownString(p.error),
	}
}
func cntPasskeyLoginFinishResponse(s *PasskeyLoginFinishResponse, cnt *uint) [0]C.PasskeyLoginFinishResponseRef {
	_ = s
	_ = cnt
	return [0]C.PasskeyLoginFinishResponseRef{}
}
func refPasskeyLoginFinishResponse(p *PasskeyLoginFinishResponse, buffer *[]byte) C.PasskeyLoginFinishResponseRef {
	return C.PasskeyLoginFinishResponseRef{
		success:       refC_bool(&p.success, buffer),
		user_id:       refString(&p.user_id, buffer),
		username:      refString(&p.username, buffer),
		session_token: refString(&p.session_token, buffer),
		error:         refString(&p.error, buffer),
	}
}

type MfaLoginBeginRequest struct {
	username  string
	mediation string
}

func newMfaLoginBeginRequest(p C.MfaLoginBeginRequestRef) MfaLoginBeginRequest {
	return MfaLoginBeginRequest{
		username:  newString(p.username),
		mediation: newString(p.mediation),
	}
}
func ownMfaLoginBeginRequest(p C.MfaLoginBeginRequestRef) MfaLoginBeginRequest {
	return MfaLoginBeginRequest{
		username:  ownString(p.username),
		mediation: ownString(p.mediation),
	}
}
func cntMfaLoginBeginRequest(s *MfaLoginBeginRequest, cnt *uint) [0]C.MfaLoginBeginRequestRef {
	_ = s
	_ = cnt
	return [0]C.MfaLoginBeginRequestRef{}
}
func refMfaLoginBeginRequest(p *MfaLoginBeginRequest, buffer *[]byte) C.MfaLoginBeginRequestRef {
	return C.MfaLoginBeginRequestRef{
		username:  refString(&p.username, buffer),
		mediation: refString(&p.mediation, buffer),
	}
}

type MfaLoginBeginResponse struct {
	session_id     string
	challenge_json string
	success        bool
	error          string
}

func newMfaLoginBeginResponse(p C.MfaLoginBeginResponseRef) MfaLoginBeginResponse {
	return MfaLoginBeginResponse{
		session_id:     newString(p.session_id),
		challenge_json: newString(p.challenge_json),
		success:        newC_bool(p.success),
		error:          newString(p.error),
	}
}
func ownMfaLoginBeginResponse(p C.MfaLoginBeginResponseRef) MfaLoginBeginResponse {
	return MfaLoginBeginResponse{
		session_id:     ownString(p.session_id),
		challenge_json: ownString(p.challenge_json),
		success:        newC_bool(p.success),
		error:          ownString(p.error),
	}
}
func cntMfaLoginBeginResponse(s *MfaLoginBeginResponse, cnt *uint) [0]C.MfaLoginBeginResponseRef {
	_ = s
	_ = cnt
	return [0]C.MfaLoginBeginResponseRef{}
}
func refMfaLoginBeginResponse(p *MfaLoginBeginResponse, buffer *[]byte) C.MfaLoginBeginResponseRef {
	return C.MfaLoginBeginResponseRef{
		session_id:     refString(&p.session_id, buffer),
		challenge_json: refString(&p.challenge_json, buffer),
		success:        refC_bool(&p.success, buffer),
		error:          refString(&p.error, buffer),
	}
}

type MfaLoginFinishRequest struct {
	session_id      string
	credential_json string
}

func newMfaLoginFinishRequest(p C.MfaLoginFinishRequestRef) MfaLoginFinishRequest {
	return MfaLoginFinishRequest{
		session_id:      newString(p.session_id),
		credential_json: newString(p.credential_json),
	}
}
func ownMfaLoginFinishRequest(p C.MfaLoginFinishRequestRef) MfaLoginFinishRequest {
	return MfaLoginFinishRequest{
		session_id:      ownString(p.session_id),
		credential_json: ownString(p.credential_json),
	}
}
func cntMfaLoginFinishRequest(s *MfaLoginFinishRequest, cnt *uint) [0]C.MfaLoginFinishRequestRef {
	_ = s
	_ = cnt
	return [0]C.MfaLoginFinishRequestRef{}
}
func refMfaLoginFinishRequest(p *MfaLoginFinishRequest, buffer *[]byte) C.MfaLoginFinishRequestRef {
	return C.MfaLoginFinishRequestRef{
		session_id:      refString(&p.session_id, buffer),
		credential_json: refString(&p.credential_json, buffer),
	}
}

type MfaLoginFinishResponse struct {
	success       bool
	user_id       string
	session_token string
	error         string
}

func newMfaLoginFinishResponse(p C.MfaLoginFinishResponseRef) MfaLoginFinishResponse {
	return MfaLoginFinishResponse{
		success:       newC_bool(p.success),
		user_id:       newString(p.user_id),
		session_token: newString(p.session_token),
		error:         newString(p.error),
	}
}
func ownMfaLoginFinishResponse(p C.MfaLoginFinishResponseRef) MfaLoginFinishResponse {
	return MfaLoginFinishResponse{
		success:       newC_bool(p.success),
		user_id:       ownString(p.user_id),
		session_token: ownString(p.session_token),
		error:         ownString(p.error),
	}
}
func cntMfaLoginFinishResponse(s *MfaLoginFinishResponse, cnt *uint) [0]C.MfaLoginFinishResponseRef {
	_ = s
	_ = cnt
	return [0]C.MfaLoginFinishResponseRef{}
}
func refMfaLoginFinishResponse(p *MfaLoginFinishResponse, buffer *[]byte) C.MfaLoginFinishResponseRef {
	return C.MfaLoginFinishResponseRef{
		success:       refC_bool(&p.success, buffer),
		user_id:       refString(&p.user_id, buffer),
		session_token: refString(&p.session_token, buffer),
		error:         refString(&p.error, buffer),
	}
}

type ChaCha20Poly1305EncryptRequest struct {
	key             []uint8
	nonce           []uint8
	plaintext       []uint8
	additional_data []uint8
}

func newChaCha20Poly1305EncryptRequest(p C.ChaCha20Poly1305EncryptRequestRef) ChaCha20Poly1305EncryptRequest {
	return ChaCha20Poly1305EncryptRequest{
		key:             new_list_mapper_primitive(newC_uint8_t)(p.key),
		nonce:           new_list_mapper_primitive(newC_uint8_t)(p.nonce),
		plaintext:       new_list_mapper_primitive(newC_uint8_t)(p.plaintext),
		additional_data: new_list_mapper_primitive(newC_uint8_t)(p.additional_data),
	}
}
func ownChaCha20Poly1305EncryptRequest(p C.ChaCha20Poly1305EncryptRequestRef) ChaCha20Poly1305EncryptRequest {
	return ChaCha20Poly1305EncryptRequest{
		key:             new_list_mapper(newC_uint8_t)(p.key),
		nonce:           new_list_mapper(newC_uint8_t)(p.nonce),
		plaintext:       new_list_mapper(newC_uint8_t)(p.plaintext),
		additional_data: new_list_mapper(newC_uint8_t)(p.additional_data),
	}
}
func cntChaCha20Poly1305EncryptRequest(s *ChaCha20Poly1305EncryptRequest, cnt *uint) [0]C.ChaCha20Poly1305EncryptRequestRef {
	_ = s
	_ = cnt
	return [0]C.ChaCha20Poly1305EncryptRequestRef{}
}
func refChaCha20Poly1305EncryptRequest(p *ChaCha20Poly1305EncryptRequest, buffer *[]byte) C.ChaCha20Poly1305EncryptRequestRef {
	return C.ChaCha20Poly1305EncryptRequestRef{
		key:             ref_list_mapper_primitive(refC_uint8_t)(&p.key, buffer),
		nonce:           ref_list_mapper_primitive(refC_uint8_t)(&p.nonce, buffer),
		plaintext:       ref_list_mapper_primitive(refC_uint8_t)(&p.plaintext, buffer),
		additional_data: ref_list_mapper_primitive(refC_uint8_t)(&p.additional_data, buffer),
	}
}

type ChaCha20Poly1305EncryptResponse struct {
	ciphertext []uint8
	success    bool
	error      string
}

func newChaCha20Poly1305EncryptResponse(p C.ChaCha20Poly1305EncryptResponseRef) ChaCha20Poly1305EncryptResponse {
	return ChaCha20Poly1305EncryptResponse{
		ciphertext: new_list_mapper_primitive(newC_uint8_t)(p.ciphertext),
		success:    newC_bool(p.success),
		error:      newString(p.error),
	}
}
func ownChaCha20Poly1305EncryptResponse(p C.ChaCha20Poly1305EncryptResponseRef) ChaCha20Poly1305EncryptResponse {
	return ChaCha20Poly1305EncryptResponse{
		ciphertext: new_list_mapper(newC_uint8_t)(p.ciphertext),
		success:    newC_bool(p.success),
		error:      ownString(p.error),
	}
}
func cntChaCha20Poly1305EncryptResponse(s *ChaCha20Poly1305EncryptResponse, cnt *uint) [0]C.ChaCha20Poly1305EncryptResponseRef {
	_ = s
	_ = cnt
	return [0]C.ChaCha20Poly1305EncryptResponseRef{}
}
func refChaCha20Poly1305EncryptResponse(p *ChaCha20Poly1305EncryptResponse, buffer *[]byte) C.ChaCha20Poly1305EncryptResponseRef {
	return C.ChaCha20Poly1305EncryptResponseRef{
		ciphertext: ref_list_mapper_primitive(refC_uint8_t)(&p.ciphertext, buffer),
		success:    refC_bool(&p.success, buffer),
		error:      refString(&p.error, buffer),
	}
}

type ChaCha20Poly1305DecryptRequest struct {
	key             []uint8
	nonce           []uint8
	ciphertext      []uint8
	additional_data []uint8
}

func newChaCha20Poly1305DecryptRequest(p C.ChaCha20Poly1305DecryptRequestRef) ChaCha20Poly1305DecryptRequest {
	return ChaCha20Poly1305DecryptRequest{
		key:             new_list_mapper_primitive(newC_uint8_t)(p.key),
		nonce:           new_list_mapper_primitive(newC_uint8_t)(p.nonce),
		ciphertext:      new_list_mapper_primitive(newC_uint8_t)(p.ciphertext),
		additional_data: new_list_mapper_primitive(newC_uint8_t)(p.additional_data),
	}
}
func ownChaCha20Poly1305DecryptRequest(p C.ChaCha20Poly1305DecryptRequestRef) ChaCha20Poly1305DecryptRequest {
	return ChaCha20Poly1305DecryptRequest{
		key:             new_list_mapper(newC_uint8_t)(p.key),
		nonce:           new_list_mapper(newC_uint8_t)(p.nonce),
		ciphertext:      new_list_mapper(newC_uint8_t)(p.ciphertext),
		additional_data: new_list_mapper(newC_uint8_t)(p.additional_data),
	}
}
func cntChaCha20Poly1305DecryptRequest(s *ChaCha20Poly1305DecryptRequest, cnt *uint) [0]C.ChaCha20Poly1305DecryptRequestRef {
	_ = s
	_ = cnt
	return [0]C.ChaCha20Poly1305DecryptRequestRef{}
}
func refChaCha20Poly1305DecryptRequest(p *ChaCha20Poly1305DecryptRequest, buffer *[]byte) C.ChaCha20Poly1305DecryptRequestRef {
	return C.ChaCha20Poly1305DecryptRequestRef{
		key:             ref_list_mapper_primitive(refC_uint8_t)(&p.key, buffer),
		nonce:           ref_list_mapper_primitive(refC_uint8_t)(&p.nonce, buffer),
		ciphertext:      ref_list_mapper_primitive(refC_uint8_t)(&p.ciphertext, buffer),
		additional_data: ref_list_mapper_primitive(refC_uint8_t)(&p.additional_data, buffer),
	}
}

type ChaCha20Poly1305DecryptResponse struct {
	plaintext []uint8
	success   bool
	error     string
}

func newChaCha20Poly1305DecryptResponse(p C.ChaCha20Poly1305DecryptResponseRef) ChaCha20Poly1305DecryptResponse {
	return ChaCha20Poly1305DecryptResponse{
		plaintext: new_list_mapper_primitive(newC_uint8_t)(p.plaintext),
		success:   newC_bool(p.success),
		error:     newString(p.error),
	}
}
func ownChaCha20Poly1305DecryptResponse(p C.ChaCha20Poly1305DecryptResponseRef) ChaCha20Poly1305DecryptResponse {
	return ChaCha20Poly1305DecryptResponse{
		plaintext: new_list_mapper(newC_uint8_t)(p.plaintext),
		success:   newC_bool(p.success),
		error:     ownString(p.error),
	}
}
func cntChaCha20Poly1305DecryptResponse(s *ChaCha20Poly1305DecryptResponse, cnt *uint) [0]C.ChaCha20Poly1305DecryptResponseRef {
	_ = s
	_ = cnt
	return [0]C.ChaCha20Poly1305DecryptResponseRef{}
}
func refChaCha20Poly1305DecryptResponse(p *ChaCha20Poly1305DecryptResponse, buffer *[]byte) C.ChaCha20Poly1305DecryptResponseRef {
	return C.ChaCha20Poly1305DecryptResponseRef{
		plaintext: ref_list_mapper_primitive(refC_uint8_t)(&p.plaintext, buffer),
		success:   refC_bool(&p.success, buffer),
		error:     refString(&p.error, buffer),
	}
}

type Ed25519GenerateKeyRequest struct {
}

func newEd25519GenerateKeyRequest(p C.Ed25519GenerateKeyRequestRef) Ed25519GenerateKeyRequest {
	return Ed25519GenerateKeyRequest{}
}
func ownEd25519GenerateKeyRequest(p C.Ed25519GenerateKeyRequestRef) Ed25519GenerateKeyRequest {
	return Ed25519GenerateKeyRequest{}
}
func cntEd25519GenerateKeyRequest(s *Ed25519GenerateKeyRequest, cnt *uint) [0]C.Ed25519GenerateKeyRequestRef {
	_ = s
	_ = cnt
	return [0]C.Ed25519GenerateKeyRequestRef{}
}
func refEd25519GenerateKeyRequest(p *Ed25519GenerateKeyRequest, buffer *[]byte) C.Ed25519GenerateKeyRequestRef {
	return C.Ed25519GenerateKeyRequestRef{}
}

type Ed25519GenerateKeyResponse struct {
	public_key  []uint8
	private_key []uint8
	success     bool
	error       string
}

func newEd25519GenerateKeyResponse(p C.Ed25519GenerateKeyResponseRef) Ed25519GenerateKeyResponse {
	return Ed25519GenerateKeyResponse{
		public_key:  new_list_mapper_primitive(newC_uint8_t)(p.public_key),
		private_key: new_list_mapper_primitive(newC_uint8_t)(p.private_key),
		success:     newC_bool(p.success),
		error:       newString(p.error),
	}
}
func ownEd25519GenerateKeyResponse(p C.Ed25519GenerateKeyResponseRef) Ed25519GenerateKeyResponse {
	return Ed25519GenerateKeyResponse{
		public_key:  new_list_mapper(newC_uint8_t)(p.public_key),
		private_key: new_list_mapper(newC_uint8_t)(p.private_key),
		success:     newC_bool(p.success),
		error:       ownString(p.error),
	}
}
func cntEd25519GenerateKeyResponse(s *Ed25519GenerateKeyResponse, cnt *uint) [0]C.Ed25519GenerateKeyResponseRef {
	_ = s
	_ = cnt
	return [0]C.Ed25519GenerateKeyResponseRef{}
}
func refEd25519GenerateKeyResponse(p *Ed25519GenerateKeyResponse, buffer *[]byte) C.Ed25519GenerateKeyResponseRef {
	return C.Ed25519GenerateKeyResponseRef{
		public_key:  ref_list_mapper_primitive(refC_uint8_t)(&p.public_key, buffer),
		private_key: ref_list_mapper_primitive(refC_uint8_t)(&p.private_key, buffer),
		success:     refC_bool(&p.success, buffer),
		error:       refString(&p.error, buffer),
	}
}

type Ed25519SignRequest struct {
	private_key []uint8
	message     []uint8
}

func newEd25519SignRequest(p C.Ed25519SignRequestRef) Ed25519SignRequest {
	return Ed25519SignRequest{
		private_key: new_list_mapper_primitive(newC_uint8_t)(p.private_key),
		message:     new_list_mapper_primitive(newC_uint8_t)(p.message),
	}
}
func ownEd25519SignRequest(p C.Ed25519SignRequestRef) Ed25519SignRequest {
	return Ed25519SignRequest{
		private_key: new_list_mapper(newC_uint8_t)(p.private_key),
		message:     new_list_mapper(newC_uint8_t)(p.message),
	}
}
func cntEd25519SignRequest(s *Ed25519SignRequest, cnt *uint) [0]C.Ed25519SignRequestRef {
	_ = s
	_ = cnt
	return [0]C.Ed25519SignRequestRef{}
}
func refEd25519SignRequest(p *Ed25519SignRequest, buffer *[]byte) C.Ed25519SignRequestRef {
	return C.Ed25519SignRequestRef{
		private_key: ref_list_mapper_primitive(refC_uint8_t)(&p.private_key, buffer),
		message:     ref_list_mapper_primitive(refC_uint8_t)(&p.message, buffer),
	}
}

type Ed25519SignResponse struct {
	signature []uint8
	success   bool
	error     string
}

func newEd25519SignResponse(p C.Ed25519SignResponseRef) Ed25519SignResponse {
	return Ed25519SignResponse{
		signature: new_list_mapper_primitive(newC_uint8_t)(p.signature),
		success:   newC_bool(p.success),
		error:     newString(p.error),
	}
}
func ownEd25519SignResponse(p C.Ed25519SignResponseRef) Ed25519SignResponse {
	return Ed25519SignResponse{
		signature: new_list_mapper(newC_uint8_t)(p.signature),
		success:   newC_bool(p.success),
		error:     ownString(p.error),
	}
}
func cntEd25519SignResponse(s *Ed25519SignResponse, cnt *uint) [0]C.Ed25519SignResponseRef {
	_ = s
	_ = cnt
	return [0]C.Ed25519SignResponseRef{}
}
func refEd25519SignResponse(p *Ed25519SignResponse, buffer *[]byte) C.Ed25519SignResponseRef {
	return C.Ed25519SignResponseRef{
		signature: ref_list_mapper_primitive(refC_uint8_t)(&p.signature, buffer),
		success:   refC_bool(&p.success, buffer),
		error:     refString(&p.error, buffer),
	}
}

type Ed25519VerifyRequest struct {
	public_key []uint8
	message    []uint8
	signature  []uint8
}

func newEd25519VerifyRequest(p C.Ed25519VerifyRequestRef) Ed25519VerifyRequest {
	return Ed25519VerifyRequest{
		public_key: new_list_mapper_primitive(newC_uint8_t)(p.public_key),
		message:    new_list_mapper_primitive(newC_uint8_t)(p.message),
		signature:  new_list_mapper_primitive(newC_uint8_t)(p.signature),
	}
}
func ownEd25519VerifyRequest(p C.Ed25519VerifyRequestRef) Ed25519VerifyRequest {
	return Ed25519VerifyRequest{
		public_key: new_list_mapper(newC_uint8_t)(p.public_key),
		message:    new_list_mapper(newC_uint8_t)(p.message),
		signature:  new_list_mapper(newC_uint8_t)(p.signature),
	}
}
func cntEd25519VerifyRequest(s *Ed25519VerifyRequest, cnt *uint) [0]C.Ed25519VerifyRequestRef {
	_ = s
	_ = cnt
	return [0]C.Ed25519VerifyRequestRef{}
}
func refEd25519VerifyRequest(p *Ed25519VerifyRequest, buffer *[]byte) C.Ed25519VerifyRequestRef {
	return C.Ed25519VerifyRequestRef{
		public_key: ref_list_mapper_primitive(refC_uint8_t)(&p.public_key, buffer),
		message:    ref_list_mapper_primitive(refC_uint8_t)(&p.message, buffer),
		signature:  ref_list_mapper_primitive(refC_uint8_t)(&p.signature, buffer),
	}
}

type Ed25519VerifyResponse struct {
	valid   bool
	success bool
	error   string
}

func newEd25519VerifyResponse(p C.Ed25519VerifyResponseRef) Ed25519VerifyResponse {
	return Ed25519VerifyResponse{
		valid:   newC_bool(p.valid),
		success: newC_bool(p.success),
		error:   newString(p.error),
	}
}
func ownEd25519VerifyResponse(p C.Ed25519VerifyResponseRef) Ed25519VerifyResponse {
	return Ed25519VerifyResponse{
		valid:   newC_bool(p.valid),
		success: newC_bool(p.success),
		error:   ownString(p.error),
	}
}
func cntEd25519VerifyResponse(s *Ed25519VerifyResponse, cnt *uint) [0]C.Ed25519VerifyResponseRef {
	_ = s
	_ = cnt
	return [0]C.Ed25519VerifyResponseRef{}
}
func refEd25519VerifyResponse(p *Ed25519VerifyResponse, buffer *[]byte) C.Ed25519VerifyResponseRef {
	return C.Ed25519VerifyResponseRef{
		valid:   refC_bool(&p.valid, buffer),
		success: refC_bool(&p.success, buffer),
		error:   refString(&p.error, buffer),
	}
}
func main() {}
